name: ios_f_n_niagaraforestcamping_3246
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # utils
  logger: ^2.5.0
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  share_plus: ^11.0.0

  # maps
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

  # state management
  flutter_bloc: ^9.0.0

  # local data saving
  shared_preferences: ^2.5.3

  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  onesignal_flutter: ^5.1.2
  appsflyer_sdk: ^6.16.21
  http: ^1.2.1
  advertising_id: ^2.0.0
  flutter_inappwebview: ^6.1.5
  external_app_launcher: ^4.0.3
  app_tracking_transparency: ^2.0.6+1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
